alias gcl "git clone"
alias svim "sudo -E nvim"
alias fm "yazi"
alias ranger "yazi"
alias almh "almh.py"
alias cp "cp -r"
alias ts "sudo -E timeshift-gtk"
alias sfm "sudo -E thunar"
alias mpdmusics "ncmpcpp -c ~/.ncmpcpp/config-art"
